routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/mpesa-test', function () {
    return view('mpesa');
});
Route::post('/mpesa-test', 'PaymentController@webPay');
Route::get('/transactions', function () {
    return view('payment');
});
Route::get('/android', "DownloadController@getDownload");

app/Payment.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $hidden = ['id', 'updated_at'];

    protected $casts = ['created_at' => 'datetime:Y-m-d'];

    public function getPayeeAttribute($value)
    {
        $exploded = explode("-", $value);
        return $exploded[0] . " Brokers";
    }

    public function getCreatedAtAttribute($value)
    {
        return (new Carbon($value))->format('d-m-Y');
    }
}

resources/views/alerts.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <a href="javascript:void(0)" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('ok'))
    <div class="main" style="margin-bottom: 0;">
        <div class="alert  alert-success">
            <a href="javascript:void(0)" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{session('ok')}}
        </div>
    </div>
@endif

@if(session()->has('error'))
    <div class="main" style="margin-bottom: 0;">
        <div class="alert alert-danger">
            <a href="javascript:void(0)" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{session('error')}}
        </div>
    </div>
@endif

resources/views/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Berke</title>
    <meta name="csrf-token" content="{{csrf_token()}}">
    <link rel="stylesheet" href="{{url('css/bootstrap.min.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{{url('css/styles.css')}}">

</head>
<body>
<div class="wrapper">
    @auth
        <nav class="sidebar">
            <ul>
                <li class="bg-primary" style="padding: 20px">
                    <b>{{auth()->user()->name}}</b>
                    <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                          style="display: none;">
                        {{ csrf_field() }}
                    </form>

                    <button class="btn btn-sm btn-danger" onclick="logOut()">Logout</button>
                </li>
                <li><a @if(request()->after =='activity')
                       style="color: inherit !important; font-weight: normal"
                       @endif href="{{url('member')}}"><img src="{{url('imgs/user.svg')}}">Profile</a></li>
                <li><a href="{{url('activity')}}"><img src="{{url('imgs/layers.svg')}}">Activities</a></li>
                <li><a href="{{url('services')}}"><img src="{{url('imgs/link.svg')}}">Ext-Services</a></li>
                <li><a href="{{url('reports')}}"><img src="{{url('imgs/folder.svg')}}">Business Intel</a></li>
                <li><a href="{{url('settings')}}"><img src="{{url('imgs/settings.svg')}}">Configuration</a></li>

                <li><a href="{{url('docs')}}">CPS API Docs <i>v1.0.0</i></a></li>
            </ul>
        </nav>
    @endauth
    <div class="content">
        @include('alerts')
        @yield('content')
    </div>
</div>
</body>

<script src="{{url('js/jquery.js')}}"></script>
<script src="{{url('js/bootstrap.min.js')}}"></script>
<script src="{{url('js/scripts.js')}}"></script>
@yield('js')
@include('include.echo')

</html>

resources/views/email.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Berke</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Raleway', sans-serif;
            font-weight: 100;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;

        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 12px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }

        .h2 {
            width: 50%;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
            color: #101010;
            text-decoration: none;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }
    </style>
</head>
<body>
<div class="content">
    @php
        $member=\App\Member::find($order->member_id);
    @endphp
    <div class="top-right" style="text-align: left">
        <h5>PO BOX 14563-100,Nairobi</h5>
        <h5>Tel :0728109567</h5>
    </div>
    <div>
        <h4 style="text-align: left"> Berke Insurance Brokers Limited</h4>
        <h4 style="text-align: left">{{"Reference No: ". $order->reference}}</h4>
        <h4 style="text-align: left">{{"Date : ". $order->created_at}}</h4>
    </div>
    <hr>
    <div>
        <div style="height: 20%;background-color: #afd9ee">
            <h3>Customer</h3>
        </div>
        <table>
            <tr>
                <td>Name</td>
                <td>{{$member->username}}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{$member->email}}</td>
            </tr>
            <tr>
                <td>Contact</td>
                <td>{{$member->phone}}</td>
            </tr>
        </table>
    </div>

    <div>
        <div style="height: 20%;background-color: #afd9ee">
            <h3>Cover Particulars</h3>
        </div>
        @php
            $insurer=\App\Insurer::find($order->order->insurer_id);
        @endphp
        <table>
            <tr>
                <td>{{$insurer->insurer_name. " ". "Insurance"}}</td>
                <td>{{$order->order->cover}}</td>
                <td>{{"Ksh ".$order->order->value."/="}}</td>
            <tr>
                <td>{{"Status:"}}</td>
                <td>{{$order->status}}</td>
                <td>{{"Date :".$order->created_at}}</td>
            </tr>
            <tr>
                <td>{{"Commencing Date :".$order->created_at}}</td>
                <td>{{"Expiry Date :".(new Carbon\Carbon($order->created_at))->addMonth()->toDayDateTimeString()}}</td>
            </tr>
        </table>

    </div>

    <div>
        <div style="height: 20%;background-color: #afd9ee">
            <h3>Payment</h3>
        </div>
        @php
            $content = \App\Payment::where("reference", $order->reference)
           ->where("status", 0)
           ->orderBy('created_at', 'desc')
           ->first();
        @endphp
        <table>
            <tr>
                <td>{{"Customer Name"}}</td>
                <td>{{$content->customer_name}}</td>
            <tr>
                <td>{{"Amount Paid"}}</td>
                <td>{{"Ksh ".$content->amount."/="}}</td>
                <td>{{"To ".$content->payee}}</td>
            </tr>
            <tr>
                <td>{{"Paid Via ".$content->pay_method}}</td>
                <td>{{"Trans ID :".$content->payment_id}}</td>
                <td>{{"Date :".$content->created_at}}</td>
            </tr>
        </table>
        <hr>
        <small>Berke Insurance Brokers Limited</small>
        <hr>
    </div>
</div>
</body>
</html>

resources/views/google1a25aba476f7ebeb.blade.php
google-site-verification: google1a25aba476f7ebeb.html

resources/views/mpesa.blade.php
@extends('report')
@section('data')
    @if(isset($message))

        <div>
            <h3 style="color: #c7254e">{{$message}}</h3>
        </div>
    @endif
    <div class="container text-center">
        <div><h2>Test Pay Bill:600000</h2></div>
        <div><h2>Test phone:254708374149///</h2></div>
        <div class="row">
            <div class="col-sm-4">

                <form action={{url('/mpesa-test')}} , method="POST">
                    {{csrf_field()}}
                    <div class="form-group">
                        <input name="phone" , type="phone" class="form-control" placeholder="Phone Number" required>
                    </div>
                    <div class="form-group">
                        <input name="amount" , type="number" class="form-control" placeholder="amount" required>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control" name="pay" , value="Make Payment">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/payment.blade.php
@extends('report')
@section('data')
    @php
        $payments=\App\Payment::all()->sortByDesc('created_at');
    @endphp
    <table class="table table-striped" id="payments-table">
        <thead>
        <tr>
            <th>Transaction ID</th>
            <th>Customer Name</th>
            <th>Amount</th>
            <th>Customer Contact</th>
            <th>Reference</th>
            <th>Date</th>
        </tr>
        </thead>
        <tr>
        </tr>
        @if(isset($payments))
            @foreach($payments as $payment)
                <tr>
                    <td>{{ $payment->payment_id }}</td>
                    <td>{{ $payment->customer_name }}</td>
                    <td>{{ $payment->amount}}</td>
                    <td>{{ $payment->customer_contact}}</td>
                    <td>{{ $payment->reference}}</td>
                    <td>{{ (new \Carbon\Carbon($payment->created_at))->format('d-m-Y')}}</td>
                </tr>
            @endforeach
        @endif
    </table>
@endsection

resources/views/report.blade.php
@extends('app')
@section('content')
    <header class="header">
        <h2>Berke Insurance Brokers Ltd</h2>
        <br>
    </header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a href="{{url('reports/mpesa-test')}}">Mpesa Test Page</a></li>
            </ul>
        </div>
    </nav>
    <div id="yield">
        @yield('data')
    </div>
@endsection